{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreKind }}
    name: {{ .Values.externalSecret.secretStoreName }}
  target:
    name: {{ include "postgresql.fullname" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName }}
        property: {{ .Values.externalSecret.remoteSecretProperty }}
{{- end }}