apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}-headless
  labels:
    app: postgres
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
      name: postgres
  selector:
    app: postgres
